name       : mate-desktop-branding
version    : '17'
release    : 35
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v17/mate-desktop-branding-17.tar.xz : ed99077ec2927bb486154f6e28647db1079ec27df0d568f42a6529923c1eaca6
license    : GPL-2.0
component  : desktop.mate
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/mate-panel/layouts/solus-live.layout
        - /usr/share/lightdm/lightdm.conf.d/20_mate_config.conf
    - material :
        - /usr/share/glib-2.0/schemas/20_mate_material.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/30_mate_material.conf
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - brisk-menu
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - mate-notification-theme-slate
    - qtstyleplugins
    - solus-artwork-mate
    - material :
        - mate-desktop-branding
        - adapta-gtk-theme
        - papirus-icon-theme
        - noto-sans-ttf
        - font-roboto-ttf
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
