name       : mate-desktop-branding
version    : 1
release    : 1
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v1/mate-desktop-branding-1.tar.xz : faa1b0f002e08f7af2b9e040d9994feab7be7aedd3ec350ee844da14a374e55a
license    : GPL-2.0
component  : desktop.mate
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - solus-artwork
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
