name       : mate-desktop-branding
version    : '19.0'
release    : 50
source     :
    - git|https://github.com/getsolus/mate-desktop-branding.git : 6a3315db274f4f42f78665a67531445e878132f9
license    : GPL-2.0-only
component  :
    - desktop.mate
    - livecd : desktop.mate
summary    :
    - Defaults for the MATE Desktop in Solus
    - livecd : Solus 4.0 MATE LiveCD configuration
description:
    - Defaults for the MATE Desktop in Solus
    - livecd : Solus 4.0 MATE LiveCD configuration.
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/40_mate_settings_livecd.gschema.override
        - /usr/share/lightdm/lightdm.conf.d/20_mate_config.conf
replaces:
    - mate-desktop-branding-fortitude
    - mate-desktop-branding-legacy
    - mate-desktop-branding-material
    - mate-desktop-branding-shared
rundeps    :
    - breeze-cursor-theme
    - brisk-menu
    - font-clear-sans-ttf
    - font-roboto-ttf
    - mate-notification-theme-slate
    - noto-sans-ttf
    - papirus-icon-theme
    - qogir-gtk-theme
    - qtstyleplugins
    - solus-artwork-mate
    - livecd :
        - mate-desktop-branding
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
