name       : mate-desktop-branding
version    : '12'
release    : 28
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v12/mate-desktop-branding-12.tar.xz : 4ac6b4b4e0b7eb566dbc05e6c10a354cb1484f676260888fb4671e0288f46abc
license    : GPL-2.0
component  : desktop.mate
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/mate-panel/layouts/solus-live.layout
        - /usr/share/lightdm/lightdm.conf.d/20_mate_config.conf
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - brisk-menu
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - mate-notification-theme-slate
    - solus-artwork-mate
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
