name       : mate-desktop-branding
version    : '19.0'
release    : 41
source     :
    - https://github.com/getsolus/mate-desktop-branding/releases/download/19.0/mate-desktop-branding-19.tar.xz : 9d5f1e67a737a850521f6992f8631993868c176e5d3cf56535df416eb3e6a65e
license    : GPL-2.0-only
component  :
    - desktop.mate
    - fortitude : desktop.mate
    - legacy : desktop.mate
    - livecd : desktop.mate
    - material : desktop.mate
    - shared : desktop.mate
summary    :
    - Defaults for the MATE Desktop in Solus
    - fortitude : Solus 4.0 Fortitude defaults for our MATE experience
    - legacy : Legacy Solus MATE desktop branding
    - livecd : Solus 4.0 MATE LiveCD configuration
    - material : Material Design inspired MATE experience
    - shared : Shared dependencies of various branding packages
description:
    - Defaults for the MATE Desktop in Solus.
    - fortitude : Solus 4.0 Fortitude defaults for our MATE experience.
    - legacy : Legacy Solus MATE desktop branding.
    - livecd : Solus 4.0 MATE LiveCD configuration.
    - material : Material Design inspired MATE experience.
    - shared : Shared dependencies of various branding packages.
patterns   :
    - fortitude :
        - /usr/share/glib-2.0/schemas/30_mate_fortitude.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/40_mate_fortitude.conf
    - legacy :
        - /usr/share/mate-desktop-branding/legacy
    - livecd :
        - /usr/share/glib-2.0/schemas/40_mate_settings_livecd.gschema.override
        - /usr/share/mate-panel/layouts/solus-live.layout
        - /usr/share/lightdm/lightdm.conf.d/20_mate_config.conf
    - material :
        - /usr/share/glib-2.0/schemas/20_mate_material.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/30_mate_material.conf
    - shared :
        - /usr/share/defaults/etc/profile.d/*
        - /usr/share/glib-2.0/schemas/10_mate_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_mate_default.conf
        - /usr/share/mate-panel/layouts/solus.layout
replaces   :
    - legacy : mate-desktop-branding
rundeps    :
    - fortitude :
        - font-roboto-ttf
        - mate-desktop-branding-shared
        - noto-sans-ttf
        - papirus-icon-theme
        - plata-theme
    - legacy :
        - arc-gtk-theme
        - arc-icon-theme
        - faba-icon-theme-mono
        - mate-desktop-branding-shared
    - material :
        - adapta-gtk-theme
        - font-roboto-ttf
        - mate-desktop-branding-legacy
        - noto-sans-ttf
        - papirus-icon-theme
    - shared :
        - breeze-cursor-theme
        - brisk-menu
        - font-clear-sans-ttf
        - mate-notification-theme-slate
        - qtstyleplugins
        - solus-artwork-mate
setup      : |
    %patch -p1 < $pkgfiles/0001-Test-setting-document-and-monospace-font-for-termina.patch
    %patch -p1 < $pkgfiles/0002-Add-GNOME-schemas-for-interface.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
    echo "I am just a legacy deps package." > $workdir/shared
    install -Dm00644 $workdir/shared $installdir/usr/share/mate-desktop-branding/legacy
