name       : mate-desktop-branding
version    : 6
release    : 10
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v6/mate-desktop-branding-6.tar.xz : aa78408dcfa037df60bb65702cd52a9b5f1fd71582793d45fa2af098429194f6
license    : GPL-2.0
component  : desktop.mate
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/mate-panel/layouts/solus-live.layout
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-snow-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - mate-notification-theme-solus
    - solus-artwork-mate
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-the-broken-launcher-on-LiveCD-incorrect-desktop-.patch
    %patch -p1 < $pkgfiles/0002-Underp-the-layouts.patch
    %patch -p1 < $pkgfiles/0003-schemas-Add-override-for-the-clock-settings.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
