name       : mate-desktop-branding
version    : 3
release    : 4
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v3/mate-desktop-branding-3.tar.xz : 9ad38096fd04f9249bb92a3164c1594870dbcbbb29f89ba9146abae847074a3f
license    : GPL-2.0
component  : desktop.mate
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - solus-artwork
    - breeze-snow-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-copy-paste-issue.patch
    %configure
build      : |
    %make
install    : |
    %make_install
