name       : mate-desktop-branding
version    : 4
release    : 5
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v4/mate-desktop-branding-4.tar.xz : 68c963b7112242eced1284cd66051a918b60fab7952b1fbc938adb37d30745df
license    : GPL-2.0
component  : desktop.mate
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - solus-artwork
    - breeze-snow-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
