name       : mate-desktop-branding
version    : '11'
release    : 26
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v11/mate-desktop-branding-11.tar.xz : 920f6d7442292e1dcfc7e12c453a7c91b35a81bf37264f2157fe6fdc81697e0b
license    : GPL-2.0
component  : desktop.mate
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/mate-panel/layouts/solus-live.layout
        - /usr/share/lightdm/lightdm.conf.d/20_mate_config.conf
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-snow-cursor-theme
    - brisk-menu
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - mate-notification-theme-slate
    - solus-artwork-mate
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
