name       : mate-desktop-branding
version    : '5'
release    : 6
source     :
    - https://github.com/solus-project/mate-desktop-branding/releases/download/v5/mate-desktop-branding-5.tar.xz : 5d5c234f4b2e9803a424438b338b1e7e39fd08267f1b23c2ab30e75974fb3c8b
license    : GPL-2.0
component  : desktop.mate
summary    : Defaults for the MATE Desktop in Solus
rundeps    :
    - solus-artwork
    - breeze-snow-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
description: |
    Defaults for the MATE Desktop in Solus
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
